### PR TITLE
Fix for modal workflow change introduced in Wagtail 2.2

### PR DESCRIPTION
**Pull request by ChickenF622**
Older method of pass JavaScript directly to render_modal_workflow was deprecated in Wagtail 2.2 and removed in Wagtail 2.4. https://docs.wagtail.io/en/v2.4/releases/2.2.html?highlight=render_modal_workflow#javascript-templates-in-modal-workflows-are-deprecated. This changes the modal workflow to use the new method.

### CODE REVIEW

**Comment by ChickenF622** [comment]
Awesome thanks. Not sure if that repo is active anymore so I have just been maintaining my own version unfortunately.

**Comment by msilvapor** [comment]
- The files ".vscode/settings.json", "PKG-INFO" and "setup.py" shouldn't have been commited
- Check for compatibility issues regarding the import of SearchForm

**Comment by DiogoMarques29** [comment]
With the introduction of Embedded Content in wagtail 1.12 https://docs.wagtail.io/en/v1.12.6/releases/1.12.html#improved-embed-configuration, this package will no longer be maintained.

**Comment by bashu** [comment]
fixed in https://github.com/bashu/wagtail-embedvideos/pull/73

**Pull request closed without merging**
