### PR TITLE
Collections

### PR DESCRIPTION
**Pull request by SalahAdDin**
Ok, i'm triying implements collections for embed videos.

I'm based in `wagtailimages` core package, made some important changes in templates and python files, and work, seems it, but i didn't tested yet. 

I miss some commits, but in this fays i'll make it.

### CODE REVIEW

**Comment by SalahAdDin** [comment]
Here an advance:
embedvideofeature

**Comment by SalahAdDin** [comment]
In current commit, i have bug:
embedvideopackage

This is the traceback:

``` bash
[12/Sep/2016 18:23:27] "GET /admin/embed_videos/chooser/ HTTP/1.1" 500 6731
Internal Server Error: /admin/embed_videos/chooser/
Traceback (most recent call last):
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/django/views/decorators/cache.py", line 43, in _cache_controlled
    response = viewfunc(request, *args, **kw)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/wagtail/wagtailadmin/decorators.py", line 24, in decorated_view
    return view_func(request, *args, **kwargs)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/wagtail_embed_videos/views/chooser.py", line 109, in chooser
    'collections': collections,
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/wagtail/wagtailadmin/modal_workflow.py", line 17, in render_modal_workflow
    html = render_to_string(html_template, template_vars or {}, request=request)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/django/test/utils.py", line 94, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/django/template/defaulttags.py", line 315, in render
    return nodelist.render(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/django/template/defaulttags.py", line 439, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/django/urls/resolvers.py", line 392, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
django.urls.exceptions.NoReverseMatch: Reverse for ' wagtail_embed_videos_add_embed_video' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
[12/Sep/2016 18:23:28] "GET /admin/embed_videos/chooser/ HTTP/1.1" 500 6731
```

**Comment by DiogoMarques29** [comment]
This PR has merge conflicts.

**Comment by SalahAdDin** [comment]
@DiogoMarques29 Which?

**Pull request closed without merging**
