### PR TITLE
Final feature PR

### PR DESCRIPTION
**Pull request by SalahAdDin**
This contains all new features:
- Collections
- ... 

I forgot all hahahaha

I think we have to test the API implementation.

### CODE REVIEW

**Comment by DiogoMarques29** [comment]
Impossible to review this PR. Please separate all features into small PR.

**Comment by SalahAdDin** [comment]
How can i do it?

It 's a very long proceduring, you can try reviewing all my other PR.

**Comment by SalahAdDin** [comment]
Splitted in next PR:
https://github.com/infoportugal/wagtail-embedvideos/pull/51
https://github.com/infoportugal/wagtail-embedvideos/pull/52
https://github.com/infoportugal/wagtail-embedvideos/pull/53
https://github.com/infoportugal/wagtail-embedvideos/pull/54
https://github.com/infoportugal/wagtail-embedvideos/pull/55
https://github.com/infoportugal/wagtail-embedvideos/pull/56

**Comment by SalahAdDin** [comment]
@DiogoMarques29 You have to review each PR in order, i will add until Collections, further fixes after you merge all PRs. Or you can see this PR.

If you find inconsistences that's because i splitted this PR in more lower PRs without taking in account the order and etc. It's because it cames from one year ago base development and i forgot it.

I took many ideas from `wagtail`'s image app.

**Pull request closed without merging**
