### PR TITLE
Final tweaks

### PR DESCRIPTION
**Pull request by SalahAdDin**
Hi man, now, it's  lastest touch for totally update.

Please merge all PR from oldest to newest for make this pr more, you know, small.

Review it and feel free to change it, thanks you!

### CODE REVIEW

**Comment by SalahAdDin** [comment]
Ok guys, the changes in setup files is because installation, current installation, give me problems:
seleccion_258
Current version, you can see a new python package: `api`, that have other packages, and a new folder, locale files folder. But, in the image can't you see these folders.

Now:
seleccion_257
But with new setup file, all packages are installed.

Please, feel free to modify this and make it better.

Thank you!

**Comment by SalahAdDin** [comment]
Ok, as we have to delete admin taggable search i propouse use methods like class ImageQuerySet(SearchableQuerySetMixin, models.QuerySet) for search in admin.

**Comment by bashu** [comment]
@SalahAdDin what a mess...

**Comment by DiogoMarques29** [comment]
Hi,
Thanks for all the commits guys.
We can't review that many commits in just one pull request, so we'll have to close this PR.
Also, the PR title should clearly state the purpose of all commits.
We are currently working on a branch that may solve some or all of your problems, including compatibility with Wagtail 1.9. You can check https://github.com/tiagofmc/wagtail-embedvideos

**Comment by SalahAdDin** [comment]
@DiogoMarques29, @bashu, @lboaretto, i merged your pull request, now is completly.

**Comment by SalahAdDin** [comment]
@DiogoMarques29 , this is the best update now.

**Pull request closed without merging**
