### PR TITLE
Made wagtail-embedvideos compatible with current Wagtail version (1.9)

### PR DESCRIPTION
**Pull request by tiagofmc**
With this changes wagtail-embedvideo is **NOT** compatible with versions <= 1.6!

- There is only one migration now;
- Changed the structure of "AbstractEmbedVideo", because "TagSearchable" is not used anymore;

### CODE REVIEW

**Comment by SalahAdDin** [comment]
👍

**Comment by SalahAdDin** [comment]
This update doesn't apply all new features for documents and images, we have development this features, poorly we know, in our branch. You close it.

**Comment by tiagofmc** [comment]
Hi @SalahAdDin,

Right now our main objective was to update wagtail_embedvideos to be compatible with the latest version of Wagtail (1.9).

Soon we will expand this package to use every new feature that was developed for documents and images.

**Comment by SalahAdDin** [comment]
Can you use my fork? I already did all of this, you can take as base and over it make other changes.

**Pull request merged**
