### PR TITLE
Localization

### PR DESCRIPTION
**Pull request by SalahAdDin**

### CODE REVIEW

**Comment by SalahAdDin** [comment]
Fell good for modify and make better this.

**Comment by SalahAdDin** [comment]
I have a problem with this current localization files: http://stackoverflow.com/questions/39443345/valueerror-plural-forms-expression-could-be-dangerous

Can anyone help me?

**Comment by DiogoMarques29** [comment]
This PR has Merge conflicts.

**Comment by SalahAdDin** [comment]
Which problems dude?

**Pull request closed without merging**
