### PR TITLE
Django 2.0 + wagtail 2.0 compatibility

### PR DESCRIPTION
**Pull request by dingosaurus**
Django 2.0 and wagtail 2.0 compatibility

### CODE REVIEW

**Comment by benpetty** [comment]
Thanks @dingosaurus would love to see this merged and rolled into a release

**Comment by DiogoMarques29** [comment]
Hi @dingosaurus, thanks for the PR.
From what i see, this makes the usage of wagtail < 2.0 impossible, am i right? Same goes for django. Can you add some notes to the documentation?

Cheers

**Comment by jayden2** [comment]
@dingosaurus going by the readme, does this mean django 1.11 + wagtail 2.0 is not supported?

**Comment by DiogoMarques29** [comment]
@jayden2 sorry, you are right. Django version 1.11 is still supported. I'll make a new release reflecting these changes.
Thanks

**Comment by DiogoMarques29** [comment]
There you go @jayden2 
Version 0.4.1 is the current latest version, and supports django>=1.11 and wagtail>=2.0

**Comment by jayden2** [comment]
Thanks for your promptness, much appreciated!

**Pull request merged**
